accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import SignupView

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

]

library/urls.py
from django.urls import path

from . import views
from .views import BookDetailView, BookListView, BookCreateView, BookUpdateView, ProposalListView, OwnedBooksListView, ApproveProposalView, RejectProposalView, ProposalCreateView

urlpatterns = [
    path('', BookListView.as_view(), name='index'),
    path('proposals/', ProposalListView.as_view(), name='proposals'),
    path('proposals/new_proposal/', ProposalCreateView.as_view(), name='new_proposal'),
    path('proposals/<int:pk>/approve/', ApproveProposalView.as_view(), name='proposal_approve'),
    path('proposals/<int:pk>/reject/', RejectProposalView.as_view(), name='proposal_reject'),
    path('my-books/', OwnedBooksListView.as_view(), name='my_books'),
    path('books/update/<int:pk>/', BookUpdateView.as_view(), name='update'),
    path('books/<int:pk>/', BookDetailView.as_view(), name='detail'),
    path('books/add/', BookCreateView.as_view(), name='add'),
]

shelfish/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('library.urls')),
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

library/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.utils import timezone

# Create your models here.

class Book(models.Model):

    BOOK_STATUS = (
        (-1, 'Not Available'),
        (0, 'Draft'),
        (1, 'Available'),
    )

    title = models.CharField(max_length=70)
    isbn = models.CharField(max_length=13, blank=True)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    listing_date = models.DateTimeField('date listed', default=timezone.now)
    description = models.TextField(max_length=1000, blank=True)
    number_of_pages = models.IntegerField(default=0)
    author = models.CharField(max_length=70, blank=True)
    owner = models.ForeignKey(User, on_delete = models.CASCADE, related_name='book_owner')
    status = models.IntegerField(choices=BOOK_STATUS, default=1)


    class Meta:
        ordering = ['-id']

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Proposal(models.Model):

    PROPOSAL_STATUS = (
        (-1, 'Rejected'),
        (0, 'Waiting'),
        (1, 'Accepted'),
    )

    requested_book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='requested_book')
    proposed_book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='proposed_book')
    proposal_date = models.DateTimeField('date published', default=timezone.now)
    status = models.IntegerField(choices=PROPOSAL_STATUS, default=0)

    def __str__(self):
        proposal_name = '{req.title} - {pro.title}'.format(req=self.requested_book, pro=self.proposed_book)
        return proposal_name

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView

# Create your views here.

class SignupView(CreateView):
    form_class = UserCreationForm
    model = User
    template_name = 'registration/signup.html'
    success_url = '/'

library/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, FormView
from django.views.generic.base import TemplateView

from django.views import View
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy

from .models import Book, Proposal

# Create your views here.

class BookListView(ListView):

    model = Book
    paginate_by = 10
    template_name = "library/index.html"


class OwnedBooksListView(LoginRequiredMixin, ListView):

    model = Book
    paginate_by = 10
    template_name = "library/my-books.html"

    def get_queryset(self):
        user = self.request.user
        return Book.objects.filter(owner=user)


class BookDetailView(DetailView):

    model = Book
    template_name = "library/detail.html"


class BookCreateView(LoginRequiredMixin, CreateView):

    model = Book
    fields = ['title', 'isbn', 'pub_date', 'description', 'number_of_pages',
            'author',  ]
    template_name = "library/add.html"

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class BookUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):

    def test_func(self):
        book = self.get_object()
        return book.owner == self.request.user

    model = Book
    fields = ['title', 'isbn', 'pub_date', 'description', 'number_of_pages',
            'author',]
    template_name = "library/update.html"


class ProposalListView(LoginRequiredMixin, TemplateView):

    template_name = "library/proposals.html"

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        context['proposed_book_list'] = Proposal.objects.filter(proposed_book__owner=user)
        context['requested_book_list'] = Proposal.objects.filter(requested_book__owner=user)
        return context


class ProposalCreateView(LoginRequiredMixin, CreateView):

    model = Proposal
    fields = ['requested_book', 'proposed_book']
    template_name = "library/new-proposal.html"
    success_url = '/proposals/'


class ApproveProposalView(LoginRequiredMixin, UserPassesTestMixin, View):

    def test_func(self):
        proposal = Proposal.objects.get(pk=self.kwargs['pk'])
        return proposal.requested_book.owner == self.request.user

    def post(self, request, *args, **kwargs):
        proposal = get_object_or_404(Proposal, pk=self.kwargs['pk'])
        proposal.status = 1
        proposal.requested_book.status = -1
        proposal.proposed_book.status = -1
        proposal.save()
        return redirect(reverse_lazy('proposals'))


class RejectProposalView(LoginRequiredMixin, UserPassesTestMixin, View):

    def test_func(self):
        proposal = Proposal.objects.get(pk=self.kwargs['pk'])
        return proposal.requested_book.owner == self.request.user

    def post(self, request, *args, **kwargs):
        proposal = get_object_or_404(Proposal, pk=self.kwargs['pk'])
        proposal.status = -1
        proposal.save()
        return redirect(reverse_lazy('proposals'))

library/templates/library/add.html
{% extends 'library/base.html' %}

{% block content %}

<h1>Add New Book</h1>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>


{% endblock %}

library/templates/library/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Shelfish - Book Exchanging Platform</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
      <a class="navbar-brand" href="{% url 'index' %}">SHELFISH</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
         <div class="navbar-nav">
           {% if user.is_authenticated %}
           <a class="nav-item nav-link" href="{% url 'my_books' %}">My Books</a>
           <a class="nav-item nav-link" href="{% url 'add' %}">Add Listing</a>
           <a class="nav-item nav-link" href="{% url 'proposals' %}">Porposals</a>
           <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
           {% else %}
           <a href="{% url 'login' %}" class="nav-item nav-link bold">Login</a>
           <a href="{% url 'signup' %}" class="nav-item nav-link bold">Signup</a>
           {% endif %}
         </div>
       </div>
    </nav>

    {% block content %}
    {% endblock %}

  </body>
</html>

library/templates/library/detail.html
{% extends 'library/base.html' %}

{% block content %}

<h1>{{ book.title }}</h1>
{% if book.owner == user %}
<a href="{% url 'update' pk=book.pk %}">Edit</a>
{% endif %}

<p>{{ book.author }}</p>
<p>{{ book.isbn }}</p>
<p>{{ book.pub_date }}</p>
<p>{{ book.number_of_pages }}</p>
<p>{{ book.description }}</p>
<p>{{ book.owner }}</p>

{% endblock %}

library/templates/library/index.html
{% extends 'library/base.html' %}

{% block content %}

<h1>Book Listing</h1>

<ul>
    {% for book in book_list %}
        <li><a href="{% url 'detail' pk=book.pk %}">{{ book.title }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

library/templates/library/my-books.html
{% extends 'library/base.html' %}

{% block content %}

<h1>My Books  </h1>

<ul>
    {% for book in book_list %}
        <li><a href="{% url 'detail' pk=book.pk %}">{{ book.title }}</a> - <a href="{% url 'update' pk=book.pk %}">Edit</a></li>
    {% endfor %}
</ul>

{% endblock %}

library/templates/library/new-proposal.html
{% extends 'library/base.html' %}

{% block content %}

<h1>New Proposal</h1>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>


{% endblock %}

library/templates/library/proposals.html
{% extends 'library/base.html' %}

{% block content %}

<h1>Proposal Listing</h1>
<br>
<a href="{% url 'new_proposal' %}">Create New Proposal</a>
<h3>Outgoing Proposals</h3>
<ul>
    {% for proposed in proposed_book_list %}
        <li>{{ proposed }} - {{ proposed.get_status_display }}</li>
    {% endfor %}
</ul>
<br>
<h3>Incoming Proposals</h3>
<ul>
    {% for requested in requested_book_list %}
        <li>{{ requested }} - {{ requested.get_status_display }}</li>
        {% if requested.status == 0 %}
        <form method="POST" action="{% url 'proposal_approve' requested.pk %}">
          {% csrf_token %}
          <button type="submit">Approve</button>
        </form>

        <form method="POST" action="{% url 'proposal_reject' requested.pk %}">
          {% csrf_token %}
          <button type="submit">Reject</button>
        </form>
      {% endif %}
    {% endfor %}
</ul>
{% endblock %}

library/templates/library/update.html
{% extends 'library/base.html' %}

{% block content %}

<h1>Update Book</h1>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Update</button>
</form>


{% endblock %}